In [2]:
import numpy as np
ar = np.array([[1,2,3],[4,5,6], [7, 8, 9]])
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [7]:
ar = np.array([[1, 2, 3], [4, 5, 6]])
ar = ar.reshape(3, 2)
ar

array([[1, 2],
       [3, 4],
       [5, 6]])

In [15]:
mat = np.arange(0, 100, 2).reshape(5, 10)
mat

array([[ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18],
       [20, 22, 24, 26, 28, 30, 32, 34, 36, 38],
       [40, 42, 44, 46, 48, 50, 52, 54, 56, 58],
       [60, 62, 64, 66, 68, 70, 72, 74, 76, 78],
       [80, 82, 84, 86, 88, 90, 92, 94, 96, 98]])

In [17]:
e = np.array([25, 50, 4, 5, 70, 20])
# np.max(e)
# np.min(e)
e.size
# np.sum(e)

6

In [18]:
r = np.zeros(50).reshape(5, 10)
r

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [29]:
s = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])
np.random.shuffle(s)
s

array([[ 4,  5,  6],
       [10, 11, 12],
       [ 7,  8,  9],
       [ 1,  2,  3]])

In [34]:
a = [1, 2, 3, 4, 5]
c = "hello"
type(a)
b = np.array(c)
# type(b)
b

array('hello', dtype='<U5')